apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"flowise"},"name":"flowise-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"flowise"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-03-04T19:28:43Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: flowise
  name: flowise-service
  namespace: default
  resourceVersion: "252533"
  uid: 88d4f52e-cb3a-4775-899e-257cb0b514c7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.232.181
  clusterIPs:
  - 34.118.232.181
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32606
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: flowise
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.171.116.93
      ipMode: VIP
